Repository AY2223S1-CS2103T-T13-2/tp, pull requests merged in 2022-10, with the labels that each got.

#25 Add feature-remark and Revise command syntaxes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story

#21 Add tagging
  src/main/java/seedu/address/logic/commands/CreateTagCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/TagCommandGroup.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CreateTagCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
  src/main/java/seedu/address/logic/parser/TagCommandGroupParser.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/TagSet.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalTags.java
Labels: type.Story

#27 Add ShowCommand
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/TargetPerson.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TargetPersonPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TargetPersonPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Story

#43 Filter based on name and tag
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterClearCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommandPredicate.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagMatchesQueryPredicate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Story

#44 UI Makeover
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/fonts/Roboto-Black.ttf
  src/main/resources/fonts/Roboto-BlackItalic.ttf
  src/main/resources/fonts/Roboto-Bold.ttf
  src/main/resources/fonts/Roboto-BoldItalic.ttf
  src/main/resources/fonts/Roboto-Italic.ttf
  src/main/resources/fonts/Roboto-Light.ttf
  src/main/resources/fonts/Roboto-LightItalic.ttf
  src/main/resources/fonts/Roboto-Medium.ttf
  src/main/resources/fonts/Roboto-MediumItalic.ttf
  src/main/resources/fonts/Roboto-Regular.ttf
  src/main/resources/fonts/Roboto-Thin.ttf
  src/main/resources/fonts/Roboto-ThinItalic.ttf
  src/main/resources/images/brand_circle_icon.png
  src/main/resources/images/rapportbook_32.png
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Enhancement, type.Chore

#45 Add related tests for show command function
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowCommandTest.java
  src/test/java/seedu/address/logic/parser/ShowCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Chore

#49 Fix issue where remarks cannot be saved.
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Chore

#50 Add tests for tagging feature
  src/main/java/seedu/address/logic/commands/CreateTagCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CreateTagCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveTagCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/model/tag/TagSetTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: type.Chore

#51 Update tag feature to support show command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
  src/main/java/seedu/address/logic/parser/TagCommandGroupParser.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/TargetPersonCard.java
  src/main/java/seedu/address/ui/TargetPersonPanel.java
  src/main/resources/view/TargetPersonCard.fxml
  src/test/java/seedu/address/logic/commands/RemoveTagCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: type.Chore

#58 Update error messages and tooltips for filter command
  src/main/java/seedu/address/logic/commands/FilterClearCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: type.Enhancement

#62 Ban specific tag names
  src/main/java/seedu/address/logic/commands/TagCommandGroup.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
Labels: type.Chore

#64 Command aliasing
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CreateMessageCommand.java
  src/main/java/seedu/address/logic/commands/CreateTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMessageCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterClearCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/GenerateMessageCommand.java
  src/main/java/seedu/address/logic/commands/ListMessageCommand.java
  src/main/java/seedu/address/logic/commands/MessageCommandGroup.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/commands/TagCommandGroup.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/MessageCommandGroupParser.java
  src/main/java/seedu/address/logic/parser/TagCommandGroupParser.java
Labels: type.Story, priority.Low

#68 Add `DeleteTagCommand`
  src/main/java/seedu/address/logic/commands/CreateTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/parser/CreateTagCommandParser.java
  src/main/java/seedu/address/logic/parser/TagCommandGroupParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tag/TagSet.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java
Labels: type.Enhancement

#80 [Docs] Add developer guide details on tag.
  docs/DeveloperGuide.md
Labels: type.Chore

#69 UI Overhaul
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/HomeCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ReminderCard.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/SecondaryPaneState.java
  src/main/java/seedu/address/ui/TargetPersonCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/WelcomePanel.java
  src/main/resources/images/fa-envelope.png
  src/main/resources/images/fa-house.png
  src/main/resources/images/fa-phone.png
  src/main/resources/images/fa-tag.png
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ReminderCard.fxml
  src/main/resources/view/TargetPersonCard.fxml
  src/main/resources/view/TargetPersonPanel.fxml
  src/main/resources/view/WelcomePanel.fxml
Labels: type.Epic

#84 [Docs] DG show command
  docs/DeveloperGuide.md
  docs/diagrams/TargetPersonClassDiagram.puml
  docs/images/TargetPersonClassDiagram.png
Labels: type.Chore

#85 [Docs] DG Filter command
  docs/DeveloperGuide.md
Labels: type.Chore

#77 [Docs] DG messages
  docs/DeveloperGuide.md
  docs/diagrams/MessageClassDiagram.puml
  docs/images/MessageClassDiagram.png
  docs/index.md
Labels: type.Chore

#67 Update FilterCommand to `AND` unrelated filters
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FilterClearCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommandPredicate.java
  src/main/java/seedu/address/logic/commands/FilterListCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagMatchesQueryPredicate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterClearCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandPredicateTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/FilterCommandPredicateStub.java
Labels: type.Enhancement

#89 Reminders
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GenerateMessageCommand.java
  src/main/java/seedu/address/logic/commands/HomeCommand.java
  src/main/java/seedu/address/logic/commands/ReminderClearCommand.java
  src/main/java/seedu/address/logic/commands/ReminderCommandGroup.java
  src/main/java/seedu/address/logic/commands/ReminderCreateCommand.java
  src/main/java/seedu/address/logic/commands/ReminderDeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/MessageCommandGroupParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ReminderCommandGroupParser.java
  src/main/java/seedu/address/logic/parser/ReminderCreateCommandParser.java
  src/main/java/seedu/address/logic/parser/ReminderDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/TagCommandGroupParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/reminder/DateTime.java
  src/main/java/seedu/address/model/reminder/ReadOnlyReminderList.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/ReminderList.java
  src/main/java/seedu/address/storage/JsonAdaptedReminder.java
  src/main/java/seedu/address/storage/JsonReminderListStorage.java
  src/main/java/seedu/address/storage/JsonSerializableReminderList.java
  src/main/java/seedu/address/storage/ReminderListStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ReminderCard.java
  src/main/java/seedu/address/ui/TargetPersonCard.java
  src/main/java/seedu/address/ui/TargetPersonPanel.java
  src/main/java/seedu/address/ui/WelcomePanel.java
  src/main/resources/view/ReminderCard.fxml
  src/main/resources/view/TargetPersonCard.fxml
  src/main/resources/view/TargetPersonPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterClearCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterListCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Epic, type.Story, priority.High

#78 Motivational quotes
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/quote/Quote.java
  src/main/java/seedu/address/model/quote/QuoteList.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/quote/QuoteListTest.java
  src/test/java/seedu/address/model/quote/QuoteTest.java
Labels: type.Story

#90 [UI] Components for Message Templates
  src/main/java/seedu/address/logic/commands/ListMessageCommand.java
  src/main/java/seedu/address/model/message/Message.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MessageTemplateCard.java
  src/main/java/seedu/address/ui/MessageTemplatePanel.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MessageTemplateCard.fxml
  src/main/resources/view/MessageTemplatePanel.fxml
  src/main/resources/view/TargetPersonCard.fxml
  src/main/resources/view/WelcomePanel.fxml
Labels: type.Enhancement

#92 Add command aliases for home, reminder, filter commands
  src/main/java/seedu/address/logic/commands/HomeCommand.java
  src/main/java/seedu/address/logic/commands/ReminderClearCommand.java
  src/main/java/seedu/address/logic/commands/ReminderCommandGroup.java
  src/main/java/seedu/address/logic/commands/ReminderDeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ReminderCommandGroupParser.java
Labels: type.Story, priority.Low

#96 Add alias for delete tag command
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/TagCommandGroup.java
  src/main/java/seedu/address/logic/parser/TagCommandGroupParser.java
Labels: type.Story, priority.Low

#95 Disallow filter with non-existant tags
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FilterClearCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/TagMatchesQueryPredicate.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
Labels: type.Enhancement

#97 Update ClearCommand to clear reminders
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: type.Bug

#100 Feature reminders test cases
  src/main/java/seedu/address/logic/commands/ReminderClearCommand.java
  src/main/java/seedu/address/logic/commands/ReminderDeleteCommand.java
  src/main/java/seedu/address/model/reminder/DateTime.java
  src/test/java/seedu/address/logic/commands/ReminderClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ReminderCreateCommandTest.java
  src/test/java/seedu/address/logic/commands/ReminderDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DateTimeParserTest.java
  src/test/java/seedu/address/logic/parser/ReminderCommandGroupParserTest.java
  src/test/java/seedu/address/logic/parser/ReminderCreateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ReminderDeleteCommandParserTest.java
  src/test/java/seedu/address/model/reminder/DateTimeTest.java
  src/test/java/seedu/address/model/reminder/ReminderListTest.java
  src/test/java/seedu/address/model/reminder/ReminderTest.java
  src/test/java/seedu/address/testutil/TypicalReminders.java
Labels: type.Chore

#103 [Docs] Update UG for reminders, show feature, and command aliases
  docs/UserGuide.md
Labels: type.Chore

#104 Fix bug where TargetPerson tag cannot be removed
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
Labels: type.Bug, severity.Medium

#99 UI fixes and enhancements
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/TargetPerson.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/TargetPersonCard.java
  src/main/java/seedu/address/ui/TargetPersonPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/WelcomePanel.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ReminderCard.fxml
  src/main/resources/view/TargetPersonCard.fxml
  src/main/resources/view/TargetPersonPanel.fxml
  src/main/resources/view/WelcomePanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Enhancement, type.Bug

#109 [Docs] UG DeleteTagCommand
  docs/UserGuide.md
Labels: priority.Medium

#110 [Docs] UG FilterList and TagDeletion Command
  docs/UserGuide.md
Labels: type.Chore

#112 Fix consecutive `{name}` not showing in `message list` command
  src/main/java/seedu/address/ui/MessageTemplateCard.java
Labels: type.Bug

#114 Tag list command
  src/main/java/seedu/address/logic/commands/ListTagCommand.java
  src/main/java/seedu/address/logic/commands/TagCommandGroup.java
  src/main/java/seedu/address/logic/parser/TagCommandGroupParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tag/TagSet.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: type.Enhancement, priority.Medium

#130 PE-D documentation reports fixes
  docs/UserGuide.md
Labels: type.Bug

#164 [Docs] Add Intro and acknowledgement to DG
  docs/DeveloperGuide.md
Labels: type.documentation

#174 [Docs] More screenshot to UG.
  docs/UserGuide.md
  docs/images/filter.png
  docs/images/message_generate.png
  docs/images/reminder.png
  docs/images/show.png
Labels: type.documentation

#176 [Docs] Update DG User Stories
  docs/DeveloperGuide.md
Labels: type.documentation

#175 [Docs] Update DG Glossary.
  docs/DeveloperGuide.md
Labels: type.documentation

#172 [Docs] Add section for tag list in UG
  docs/UserGuide.md
Labels: type.Chore

#182 Delete `Person` shown will return to home panel
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: type.Bug

#179 [Docs] Add reminders implementation in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/MessageClassDiagram.puml
  docs/diagrams/ReminderClassDiagram.puml
  docs/diagrams/TargetPersonClassDiagram.puml
  docs/images/MessageClassDiagram.png
  docs/images/ReminderClassDiagram.png
  docs/images/TargetPersonClassDiagram.png
Labels: type.documentation

#185 Fix tag delete not updating show panel
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bug
